== NOTE: 
- this forked repo is heavily dependent on neo4j python course's sandbox instance which expires every 3-7 days. 
- It is affected by the sandbox instance and the gitpod workspace ip address or maybe local ip address. 
- It requires starting a new workspace from the course then cloning and rebase while pulling.


- Running locally-
- requires changing up the .env file (dont push that file since it contains credentials for sandbox)
- clone the repo
- create env and install requiremnts.txt
- run the flask app for UI - use set export instead of just export


= Building Neo4j Applications with Python


> Learn how to interact with Neo4j from Python using the Neo4j Python Driver

This repository accompanies the link:https://graphacademy.neo4j.com/courses/app-python/[Building Neo4j Applications with Python course^] on link:https://graphacademy.neo4j.com/[Neo4j GraphAcademy^].

For a complete walkthrough of this repository,  link:https://graphacademy.neo4j.com/courses/app-python/[enroll now^].

== A Note on comments

You may spot a number of comments in this repository that look a little like this:

[source,python]
----
# tag::something[]
someCode()
# end::something[]
----


We use link:https://asciidoc-py.github.io/index.html[Asciidoc^] to author our courses.
Using these tags means that we can use a macro to include portions of code directly into the course itself.

From the point of view of the course, you can go ahead and ignore them.


== Setting up your environment

[source,sh]
----
python -m venv neoflix

source neoflix/bin/activate
----



== Running the Application

[source,sh]
export FLASK_APP=api
export FLASK_ENV=development
flask run

== Unit Tests (only if the connection to a sandbox instance is present)-

1) pytest tests/01_connect_to_neo4j__test.py

2) pytest -s tests/02_movie_list__test.py

3) pytest tests/03_registering_a_user__test.py

4) pytest tests/04_handle_constraint_errors__test.py

5) pytest tests/05_authentication__test.py

6) pytest tests/06_rating_movies__test.py

7) pytest tests/07_favorites_list__test.py

8) 

9)

10)